package com.huiwu.temperaturecontrol.sqlite.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.huiwu.temperaturecontrol.sqlite.bean.RfidGood;
import com.huiwu.temperaturecontrol.sqlite.bean.GoodsType;
import com.huiwu.temperaturecontrol.sqlite.bean.Picture;
import com.huiwu.temperaturecontrol.sqlite.bean.TagInfo;

import com.huiwu.temperaturecontrol.sqlite.dao.RfidGoodDao;
import com.huiwu.temperaturecontrol.sqlite.dao.GoodsTypeDao;
import com.huiwu.temperaturecontrol.sqlite.dao.PictureDao;
import com.huiwu.temperaturecontrol.sqlite.dao.TagInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rfidGoodDaoConfig;
    private final DaoConfig goodsTypeDaoConfig;
    private final DaoConfig pictureDaoConfig;
    private final DaoConfig tagInfoDaoConfig;

    private final RfidGoodDao rfidGoodDao;
    private final GoodsTypeDao goodsTypeDao;
    private final PictureDao pictureDao;
    private final TagInfoDao tagInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rfidGoodDaoConfig = daoConfigMap.get(RfidGoodDao.class).clone();
        rfidGoodDaoConfig.initIdentityScope(type);

        goodsTypeDaoConfig = daoConfigMap.get(GoodsTypeDao.class).clone();
        goodsTypeDaoConfig.initIdentityScope(type);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        tagInfoDaoConfig = daoConfigMap.get(TagInfoDao.class).clone();
        tagInfoDaoConfig.initIdentityScope(type);

        rfidGoodDao = new RfidGoodDao(rfidGoodDaoConfig, this);
        goodsTypeDao = new GoodsTypeDao(goodsTypeDaoConfig, this);
        pictureDao = new PictureDao(pictureDaoConfig, this);
        tagInfoDao = new TagInfoDao(tagInfoDaoConfig, this);

        registerDao(RfidGood.class, rfidGoodDao);
        registerDao(GoodsType.class, goodsTypeDao);
        registerDao(Picture.class, pictureDao);
        registerDao(TagInfo.class, tagInfoDao);
    }

    public void clear() {
        rfidGoodDaoConfig.getIdentityScope().clear();
        goodsTypeDaoConfig.getIdentityScope().clear();
        pictureDaoConfig.getIdentityScope().clear();
        tagInfoDaoConfig.getIdentityScope().clear();
    }

    public RfidGoodDao getRfidGoodDao() {
        return rfidGoodDao;
    }

    public GoodsTypeDao getGoodsTypeDao() {
        return goodsTypeDao;
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

    public TagInfoDao getTagInfoDao() {
        return tagInfoDao;
    }

}
