package com.huiwu.temperaturecontrol.sqlite.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huiwu.temperaturecontrol.sqlite.bean.TagInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "TAG_INFO".
 */
public class TagInfoDao extends AbstractDao<TagInfo, Long> {

    public static final String TABLENAME = "TAG_INFO";

    /**
     * Properties of entity TagInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uid = new Property(1, String.class, "uid", false, "UID");
        public final static Property Linkuuid = new Property(2, String.class, "linkuuid", false, "LINKUUID");
        public final static Property Box = new Property(3, String.class, "box", false, "BOX");
        public final static Property Goods = new Property(4, String.class, "goods", false, "GOODS");
        public final static Property Object = new Property(5, String.class, "object", false, "OBJECT");
        public final static Property Bover = new Property(6, Boolean.class, "bover", false, "BOVER");
        public final static Property ReadTime = new Property(7, long.class, "readTime", false, "READ_TIME");
        public final static Property StartTime = new Property(8, long.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(9, long.class, "endTime", false, "END_TIME");
        public final static Property DelayTime = new Property(10, int.class, "delayTime", false, "DELAY_TIME");
        public final static Property Power = new Property(11, int.class, "power", false, "POWER");
        public final static Property RecordStatus = new Property(12, int.class, "recordStatus", false, "RECORD_STATUS");
        public final static Property TempMin = new Property(13, double.class, "tempMin", false, "TEMP_MIN");
        public final static Property TempMax = new Property(14, double.class, "tempMax", false, "TEMP_MAX");
        public final static Property HumMin = new Property(15, double.class, "humMin", false, "HUM_MIN");
        public final static Property HumMax = new Property(16, double.class, "humMax", false, "HUM_MAX");
        public final static Property IsOutLimit = new Property(17, boolean.class, "isOutLimit", false, "IS_OUT_LIMIT");
        public final static Property Dataarray = new Property(18, String.class, "dataarray", false, "DATAARRAY");
        public final static Property HumidityArray = new Property(19, String.class, "humidityArray", false, "HUMIDITY_ARRAY");
        public final static Property JustTemp = new Property(20, boolean.class, "justTemp", false, "JUST_TEMP");
        public final static Property RoundCircle = new Property(21, int.class, "roundCircle", false, "ROUND_CIRCLE");
        public final static Property Number = new Property(22, int.class, "number", false, "NUMBER");
        public final static Property Havepost = new Property(23, boolean.class, "havepost", false, "HAVEPOST");
    }

    ;


    public TagInfoDao(DaoConfig config) {
        super(config);
    }

    public TagInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAG_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UID\" TEXT ," + // 1: uid
                "\"LINKUUID\" TEXT ," + // 2: linkuuid
                "\"BOX\" TEXT," + // 3: box
                "\"GOODS\" TEXT," + // 4: goods
                "\"OBJECT\" TEXT," + // 5: object
                "\"BOVER\" INTEGER  DEFAULT 0," + // 6: bover
                "\"READ_TIME\" INTEGER DEFAULT 0," + // 7: readTime
                "\"START_TIME\" INTEGER DEFAULT 0," + // 8: startTime
                "\"END_TIME\" INTEGER DEFAULT 0," + // 9: endTime
                "\"DELAY_TIME\" INTEGER DEFAULT 0," + // 10: delayTime
                "\"POWER\" INTEGER DEFAULT 0," + // 11: power
                "\"RECORD_STATUS\" INTEGER DEFAULT 0," + // 12: recordStatus
                "\"TEMP_MIN\" REAL DEFAULT 0," + // 13: tempMin
                "\"TEMP_MAX\" REAL DEFAULT 0," + // 14: tempMax
                "\"HUM_MIN\" REAL DEFAULT 0," + // 15: humMin
                "\"HUM_MAX\" REAL DEFAULT 0," + // 16: humMax
                "\"IS_OUT_LIMIT\" INTEGER DEFAULT 0," + // 17: isOutLimit
                "\"DATAARRAY\" TEXT," + // 18: dataarray
                "\"HUMIDITY_ARRAY\" TEXT ," + // 19: humidityArray
                "\"JUST_TEMP\" INTEGER DEFAULT 0," + // 20: justTemp
                "\"ROUND_CIRCLE\" INTEGER DEFAULT 0," + // 21: roundCircle
                "\"NUMBER\" INTEGER DEFAULT 0," + // 22: number
                "\"HAVEPOST\" INTEGER DEFAULT 0);"); // 23: havepost
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAG_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TagInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUid());
        stmt.bindString(3, entity.getLinkuuid());
 
        String box = entity.getBox();
        if (box != null) {
            stmt.bindString(4, box);
        }
 
        String goods = entity.getGoods();
        if (goods != null) {
            stmt.bindString(5, goods);
        }
 
        String object = entity.getObject();
        if (object != null) {
            stmt.bindString(6, object);
        }

        Boolean bover = entity.isBover();
        if (bover != null) {
            stmt.bindLong(7, bover ? 1L: 0L);
        }
        stmt.bindLong(8, entity.getReadTime());
        stmt.bindLong(9, entity.getStartTime());
        stmt.bindLong(10, entity.getEndTime());
        stmt.bindLong(11, entity.getDelayTime());
        stmt.bindLong(12, entity.getPower());
        stmt.bindLong(13, entity.getRecordStatus());
        stmt.bindDouble(14, entity.getTempMin());
        stmt.bindDouble(15, entity.getTempMax());
        stmt.bindDouble(16, entity.getHumMin());
        stmt.bindDouble(17, entity.getHumMax());
        stmt.bindLong(18, entity.isOutLimit() ? 1L: 0L);
 
        String dataarray = entity.getDataarray();
        if (dataarray != null) {
            stmt.bindString(19, dataarray);
        }
        stmt.bindString(20, entity.getHumidityArray());
        stmt.bindLong(21, entity.isJustTemp() ? 1L : 0L);
        stmt.bindLong(22, entity.getRoundCircle());
        stmt.bindLong(23, entity.getNumber());
        stmt.bindLong(24, entity.isHavepost() ? 1L: 0L);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public TagInfo readEntity(Cursor cursor, int offset) {
        TagInfo entity = new TagInfo( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getString(offset + 1), // uid
                cursor.getString(offset + 2), // linkuuid
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // box
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // goods
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // object
                cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // bover
                cursor.getLong(offset + 7), // readTime
                cursor.getLong(offset + 8), // startTime
                cursor.getLong(offset + 9), // endTime
                cursor.getInt(offset + 10), // delayTime
                cursor.getInt(offset + 11), // power
                cursor.getInt(offset + 12), // recordStatus
                cursor.getDouble(offset + 13), // tempMin
                cursor.getDouble(offset + 14), // tempMax
                cursor.getDouble(offset + 15), // humMin
                cursor.getDouble(offset + 16), // humMax
                cursor.getShort(offset + 17) != 0, // isOutLimit
                cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // dataarray
                cursor.getString(offset + 19), // humidityArray
                cursor.getShort(offset + 20) != 0, // justTemp
                cursor.getInt(offset + 21), // roundCircle
                cursor.getInt(offset + 22), // number
                cursor.getShort(offset + 23) != 0 // havepost
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TagInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUid(cursor.getString(offset + 1));
        entity.setLinkuuid(cursor.getString(offset + 2));
        entity.setBox(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGoods(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setObject(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBover(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setReadTime(cursor.getLong(offset + 7));
        entity.setStartTime(cursor.getLong(offset + 8));
        entity.setEndTime(cursor.getLong(offset + 9));
        entity.setDelayTime(cursor.getInt(offset + 10));
        entity.setPower(cursor.getInt(offset + 11));
        entity.setRecordStatus(cursor.getInt(offset + 12));
        entity.setTempMin(cursor.getDouble(offset + 13));
        entity.setTempMax(cursor.getDouble(offset + 14));
        entity.setHumMin(cursor.getDouble(offset + 15));
        entity.setHumMax(cursor.getDouble(offset + 16));
        entity.setOutLimit(cursor.getShort(offset + 17) != 0);
        entity.setDataarray(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setHumidityArray(cursor.getString(offset + 19));
        entity.setJustTemp(cursor.getShort(offset + 20) != 0);
        entity.setRoundCircle(cursor.getInt(offset + 21));
        entity.setNumber(cursor.getInt(offset + 22));
        entity.setHavepost(cursor.getShort(offset + 23) != 0);
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TagInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(TagInfo entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
