package com.huiwu.temperaturecontrol.sqlite.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "GOODS_TYPE".
 */
public class GoodsType implements Parcelable {

    private long id;
    private String company;
    private int companyid;
    private String parentgoodtype;
    private String goodtype;
    private int onetime;
    private int hightmpnumber;
    private int lowtmpnumber;
    private int parentid;
    private String createtime;
    private int highhumiditynumber;
    private int lowhumiditynumber;

    public GoodsType() {
    }

    public GoodsType(Long id) {
        this.id = id;
    }

    public GoodsType(long id, String company, int companyid, String parentgoodtype, String goodtype, int onetime, int hightmpnumber, int lowtmpnumber, int parentid, String createtime, int highhumiditynumber, int lowhumiditynumber) {
        this.id = id;
        this.company = company;
        this.companyid = companyid;
        this.parentgoodtype = parentgoodtype;
        this.goodtype = goodtype;
        this.onetime = onetime;
        this.hightmpnumber = hightmpnumber;
        this.lowtmpnumber = lowtmpnumber;
        this.parentid = parentid;
        this.createtime = createtime;
        this.highhumiditynumber = highhumiditynumber;
        this.lowhumiditynumber = lowhumiditynumber;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public int getCompanyid() {
        return companyid;
    }

    public void setCompanyid(int companyid) {
        this.companyid = companyid;
    }

    public String getParentgoodtype() {
        return parentgoodtype;
    }

    public void setParentgoodtype(String parentgoodtype) {
        this.parentgoodtype = parentgoodtype;
    }

    public String getGoodtype() {
        return goodtype;
    }

    public void setGoodtype(String goodtype) {
        this.goodtype = goodtype;
    }

    public int getOnetime() {
        return onetime;
    }

    public void setOnetime(int onetime) {
        this.onetime = onetime;
    }

    public int getHightmpnumber() {
        return hightmpnumber;
    }

    public void setHightmpnumber(int hightmpnumber) {
        this.hightmpnumber = hightmpnumber;
    }

    public int getLowtmpnumber() {
        return lowtmpnumber;
    }

    public void setLowtmpnumber(int lowtmpnumber) {
        this.lowtmpnumber = lowtmpnumber;
    }

    public int getParentid() {
        return parentid;
    }

    public void setParentid(int parentid) {
        this.parentid = parentid;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public int getHighhumiditynumber() {
        return highhumiditynumber;
    }

    public void setHighhumiditynumber(int highhumiditynumber) {
        this.highhumiditynumber = highhumiditynumber;
    }

    public int getLowhumiditynumber() {
        return lowhumiditynumber;
    }

    public void setLowhumiditynumber(int lowhumiditynumber) {
        this.lowhumiditynumber = lowhumiditynumber;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.id);
        dest.writeString(this.company);
        dest.writeInt(this.companyid);
        dest.writeString(this.parentgoodtype);
        dest.writeString(this.goodtype);
        dest.writeInt(this.onetime);
        dest.writeInt(this.hightmpnumber);
        dest.writeInt(this.lowtmpnumber);
        dest.writeInt(this.parentid);
        dest.writeString(this.createtime);
        dest.writeInt(this.highhumiditynumber);
        dest.writeInt(this.lowhumiditynumber);
    }

    protected GoodsType(Parcel in) {
        this.id = in.readLong();
        this.company = in.readString();
        this.companyid = in.readInt();
        this.parentgoodtype = in.readString();
        this.goodtype = in.readString();
        this.onetime = in.readInt();
        this.hightmpnumber = in.readInt();
        this.lowtmpnumber = in.readInt();
        this.parentid = in.readInt();
        this.createtime = in.readString();
        this.highhumiditynumber = in.readInt();
        this.lowhumiditynumber = in.readInt();
    }

    public static final Creator<GoodsType> CREATOR = new Creator<GoodsType>() {
        @Override
        public GoodsType createFromParcel(Parcel source) {
            return new GoodsType(source);
        }

        @Override
        public GoodsType[] newArray(int size) {
            return new GoodsType[size];
        }
    };
}
