package com.huiwu.temperaturecontrol.sqlite.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "PICTURE".
 */
public class Picture implements Parcelable {

    private Long id;
    /**
     * Not-null value.
     */
    private String boxno;
    /** Not-null value. */
    private String linkuuid;
    /** Not-null value. */
    private String file;
    /** Not-null value. */
    private String sealOropen;
    private boolean havepost;

    public Picture() {
    }

    public Picture(Long id) {
        this.id = id;
    }

    public Picture(Long id, String boxno, String linkuuid, String file, String sealOropen, boolean havepost) {
        this.id = id;
        this.boxno = boxno;
        this.linkuuid = linkuuid;
        this.file = file;
        this.sealOropen = sealOropen;
        this.havepost = havepost;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBoxno() {
        return boxno;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBoxno(String boxno) {
        this.boxno = boxno;
    }

    /** Not-null value. */
    public String getLinkuuid() {
        return linkuuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLinkuuid(String linkuuid) {
        this.linkuuid = linkuuid;
    }

    /** Not-null value. */
    public String getFile() {
        return file;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFile(String file) {
        this.file = file;
    }

    /** Not-null value. */
    public String getSealOropen() {
        return sealOropen;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSealOropen(String sealOropen) {
        this.sealOropen = sealOropen;
    }

    public boolean getHavepost() {
        return havepost;
    }

    public void setHavepost(boolean havepost) {
        this.havepost = havepost;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.boxno);
        dest.writeString(this.linkuuid);
        dest.writeString(this.file);
        dest.writeString(this.sealOropen);
        dest.writeByte(this.havepost ? (byte) 1 : (byte) 0);
    }

    protected Picture(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.boxno = in.readString();
        this.linkuuid = in.readString();
        this.file = in.readString();
        this.sealOropen = in.readString();
        this.havepost = in.readByte() != 0;
    }

    public static final Parcelable.Creator<Picture> CREATOR = new Parcelable.Creator<Picture>() {
        @Override
        public Picture createFromParcel(Parcel source) {
            return new Picture(source);
        }

        @Override
        public Picture[] newArray(int size) {
            return new Picture[size];
        }
    };
}
