package com.huiwu.temperaturecontrol.sqlite.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "RFID_GOOD".
 */
public class RfidGood implements Parcelable, Comparable {

    private Long id;
    private int rfidgoodid;
    private String rfidgoodname;
    private int companyid;
    private String company;

    @Override
    public String toString() {
        return rfidgoodname;
    }

    public RfidGood() {
    }

    public RfidGood(Long id) {
        this.id = id;
    }

    public RfidGood(Long id, int rfidgoodid, String rfidgoodname, int companyid, String company) {
        this.id = id;
        this.rfidgoodid = rfidgoodid;
        this.rfidgoodname = rfidgoodname;
        this.companyid = companyid;
        this.company = company;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRfidgoodid() {
        return rfidgoodid;
    }

    public void setRfidgoodid(int rfidgoodid) {
        this.rfidgoodid = rfidgoodid;
    }

    public String getRfidgoodname() {
        return rfidgoodname;
    }

    public void setRfidgoodname(String rfidgoodname) {
        this.rfidgoodname = rfidgoodname;
    }

    public int getCompanyid() {
        return companyid;
    }

    public void setCompanyid(int companyid) {
        this.companyid = companyid;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @Override
    public int compareTo(Object another) {
        if (another instanceof RfidGood) {
            RfidGood rfidGood = (RfidGood) another;
            return rfidgoodname.compareTo(rfidGood.getRfidgoodname());
        }
        return 0;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeInt(this.rfidgoodid);
        dest.writeString(this.rfidgoodname);
        dest.writeInt(this.companyid);
        dest.writeString(this.company);
    }

    protected RfidGood(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.rfidgoodid = in.readInt();
        this.rfidgoodname = in.readString();
        this.companyid = in.readInt();
        this.company = in.readString();
    }

    public static final Creator<RfidGood> CREATOR = new Creator<RfidGood>() {
        @Override
        public RfidGood createFromParcel(Parcel source) {
            return new RfidGood(source);
        }

        @Override
        public RfidGood[] newArray(int size) {
            return new RfidGood[size];
        }
    };
}
