package com.huiwu.temperaturecontrol.sqlite.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "TAG_INFO".
 */
public class TagInfo {

    private Long id;
    /**
     * Not-null value.
     */
    private String uid;
    /**
     * Not-null value.
     */
    private String linkuuid;
    private String box;
    private String goods;
    private String object;
    private Boolean bover;
    private Long readTime;
    private Long startTime;
    private Long endTime;
    private Integer power;
    private Integer recordStatus;
    private Double tempMin;
    private Double tempMax;
    private Double humMin;
    private Double humMax;
    private Boolean isOutLimit;
    private String dataarray;
    private String humidityArray;
    private Boolean justTemp;
    private Integer roundCircle;
    private Integer number;
    private Boolean havepost;

    public TagInfo() {
    }

    public TagInfo(Long id) {
        this.id = id;
    }

    public TagInfo(Long id, String uid, String linkuuid, String box, String goods, String object, Boolean bover, Long readTime, Long startTime, Long endTime, Integer power, Integer recordStatus, Double tempMin, Double tempMax, Double humMin, Double humMax, Boolean isOutLimit, String dataarray, String humidityArray, Boolean justTemp, Integer roundCircle, Integer number, Boolean havepost) {
        this.id = id;
        this.uid = uid;
        this.linkuuid = linkuuid;
        this.box = box;
        this.goods = goods;
        this.object = object;
        this.bover = bover;
        this.readTime = readTime;
        this.startTime = startTime;
        this.endTime = endTime;
        this.power = power;
        this.recordStatus = recordStatus;
        this.tempMin = tempMin;
        this.tempMax = tempMax;
        this.humMin = humMin;
        this.humMax = humMax;
        this.isOutLimit = isOutLimit;
        this.dataarray = dataarray;
        this.humidityArray = humidityArray;
        this.justTemp = justTemp;
        this.roundCircle = roundCircle;
        this.number = number;
        this.havepost = havepost;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getUid() {
        return uid;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * Not-null value.
     */
    public String getLinkuuid() {
        return linkuuid;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setLinkuuid(String linkuuid) {
        this.linkuuid = linkuuid;
    }

    public String getBox() {
        return box;
    }

    public void setBox(String box) {
        this.box = box;
    }

    public String getGoods() {
        return goods;
    }

    public void setGoods(String goods) {
        this.goods = goods;
    }

    public String getObject() {
        return object;
    }

    public void setObject(String object) {
        this.object = object;
    }

    public Boolean getBover() {
        return bover;
    }

    public void setBover(Boolean bover) {
        this.bover = bover;
    }

    public Long getReadTime() {
        return readTime;
    }

    public void setReadTime(Long readTime) {
        this.readTime = readTime;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Integer getPower() {
        return power;
    }

    public void setPower(Integer power) {
        this.power = power;
    }

    public Integer getRecordStatus() {
        return recordStatus;
    }

    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    public Double getTempMin() {
        return tempMin;
    }

    public void setTempMin(Double tempMin) {
        this.tempMin = tempMin;
    }

    public Double getTempMax() {
        return tempMax;
    }

    public void setTempMax(Double tempMax) {
        this.tempMax = tempMax;
    }

    public Double getHumMin() {
        return humMin;
    }

    public void setHumMin(Double humMin) {
        this.humMin = humMin;
    }

    public Double getHumMax() {
        return humMax;
    }

    public void setHumMax(Double humMax) {
        this.humMax = humMax;
    }

    public Boolean getIsOutLimit() {
        return isOutLimit;
    }

    public void setIsOutLimit(Boolean isOutLimit) {
        this.isOutLimit = isOutLimit;
    }

    public String getDataarray() {
        return dataarray;
    }

    public void setDataarray(String dataarray) {
        this.dataarray = dataarray;
    }

    public String getHumidityArray() {
        return humidityArray;
    }

    public void setHumidityArray(String humidityArray) {
        this.humidityArray = humidityArray;
    }

    public Boolean getJustTemp() {
        return justTemp;
    }

    public void setJustTemp(Boolean justTemp) {
        this.justTemp = justTemp;
    }

    public Integer getRoundCircle() {
        return roundCircle;
    }

    public void setRoundCircle(Integer roundCircle) {
        this.roundCircle = roundCircle;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Boolean getHavepost() {
        return havepost;
    }

    public void setHavepost(Boolean havepost) {
        this.havepost = havepost;
    }

}
