package com.huiwu.temperaturecontrol.sqlite.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "TAG_INFO".
 */
public class TagInfo implements Parcelable {

    private Long id;
    /**
     * Not-null value.
     */
    private String uid;
    /**
     * Not-null value.
     */
    private String linkuuid;
    private String box = "{}";
    private String goods = "{}";
    private String object;
    private boolean bover;
    private long readTime;
    private long startTime;
    private long endTime;
    private int delayTime = 1;
    private int power;
    private int recordStatus;
    private double tempMin;
    private double tempMax;
    private double humMin;
    private double humMax;
    private boolean isOutLimit;
    private String dataarray = "[]";
    private String humidityArray = "[]";
    private boolean justTemp;
    private int roundCircle;
    private int number;
    private boolean havepost;

    public TagInfo() {
    }

    public TagInfo(Long id) {
        this.id = id;
    }

    public TagInfo(Long id, String uid, String linkuuid, String box, String goods, String object, boolean bover, long readTime, long startTime, long endTime, int delayTime, int power, int recordStatus, double tempMin, double tempMax, double humMin, double humMax, boolean isOutLimit, String dataarray, String humidityArray, boolean justTemp, int roundCircle, int number, boolean havepost) {
        this.id = id;
        this.uid = uid;
        this.linkuuid = linkuuid;
        this.box = box;
        this.goods = goods;
        this.object = object;
        this.bover = bover;
        this.readTime = readTime;
        this.startTime = startTime;
        this.endTime = endTime;
        this.delayTime = delayTime;
        this.power = power;
        this.recordStatus = recordStatus;
        this.tempMin = tempMin;
        this.tempMax = tempMax;
        this.humMin = humMin;
        this.humMax = humMax;
        this.isOutLimit = isOutLimit;
        this.dataarray = dataarray;
        this.humidityArray = humidityArray;
        this.justTemp = justTemp;
        this.roundCircle = roundCircle;
        this.number = number;
        this.havepost = havepost;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getLinkuuid() {
        return linkuuid;
    }

    public void setLinkuuid(String linkuuid) {
        this.linkuuid = linkuuid;
    }

    public String getBox() {
        return box;
    }

    public void setBox(String box) {
        this.box = box;
    }

    public String getGoods() {
        return goods;
    }

    public void setGoods(String goods) {
        this.goods = goods;
    }

    public String getObject() {
        return object;
    }

    public void setObject(String object) {
        this.object = object;
    }

    public boolean isBover() {
        return bover;
    }

    public void setBover(boolean bover) {
        this.bover = bover;
    }

    public long getReadTime() {
        return readTime;
    }

    public void setReadTime(long readTime) {
        this.readTime = readTime;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    public int getDelayTime() {
        return delayTime;
    }

    public void setDelayTime(int delayTime) {
        this.delayTime = delayTime;
    }

    public int getPower() {
        return power;
    }

    public void setPower(int power) {
        this.power = power;
    }

    public int getRecordStatus() {
        return recordStatus;
    }

    public void setRecordStatus(int recordStatus) {
        this.recordStatus = recordStatus;
    }

    public double getTempMin() {
        return tempMin;
    }

    public void setTempMin(double tempMin) {
        this.tempMin = tempMin;
    }

    public double getTempMax() {
        return tempMax;
    }

    public void setTempMax(double tempMax) {
        this.tempMax = tempMax;
    }

    public double getHumMin() {
        return humMin;
    }

    public void setHumMin(double humMin) {
        this.humMin = humMin;
    }

    public double getHumMax() {
        return humMax;
    }

    public void setHumMax(double humMax) {
        this.humMax = humMax;
    }

    public boolean isOutLimit() {
        return isOutLimit;
    }

    public void setOutLimit(boolean outLimit) {
        isOutLimit = outLimit;
    }

    public String getDataarray() {
        return dataarray;
    }

    public void setDataarray(String dataarray) {
        this.dataarray = dataarray;
    }

    public String getHumidityArray() {
        return humidityArray;
    }

    public void setHumidityArray(String humidityArray) {
        this.humidityArray = humidityArray;
    }

    public boolean isJustTemp() {
        return justTemp;
    }

    public void setJustTemp(boolean justTemp) {
        this.justTemp = justTemp;
    }

    public int getRoundCircle() {
        return roundCircle;
    }

    public void setRoundCircle(int roundCircle) {
        this.roundCircle = roundCircle;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public boolean isHavepost() {
        return havepost;
    }

    public void setHavepost(boolean havepost) {
        this.havepost = havepost;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.uid);
        dest.writeString(this.linkuuid);
        dest.writeString(this.box);
        dest.writeString(this.goods);
        dest.writeString(this.object);
        dest.writeByte(this.bover ? (byte) 1 : (byte) 0);
        dest.writeLong(this.readTime);
        dest.writeLong(this.startTime);
        dest.writeLong(this.endTime);
        dest.writeInt(this.delayTime);
        dest.writeInt(this.power);
        dest.writeInt(this.recordStatus);
        dest.writeDouble(this.tempMin);
        dest.writeDouble(this.tempMax);
        dest.writeDouble(this.humMin);
        dest.writeDouble(this.humMax);
        dest.writeByte(this.isOutLimit ? (byte) 1 : (byte) 0);
        dest.writeString(this.dataarray);
        dest.writeString(this.humidityArray);
        dest.writeByte(this.justTemp ? (byte) 1 : (byte) 0);
        dest.writeInt(this.roundCircle);
        dest.writeInt(this.number);
        dest.writeByte(this.havepost ? (byte) 1 : (byte) 0);
    }

    protected TagInfo(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.uid = in.readString();
        this.linkuuid = in.readString();
        this.box = in.readString();
        this.goods = in.readString();
        this.object = in.readString();
        this.bover = in.readByte() != 0;
        this.readTime = in.readLong();
        this.startTime = in.readLong();
        this.endTime = in.readLong();
        this.delayTime = in.readInt();
        this.power = in.readInt();
        this.recordStatus = in.readInt();
        this.tempMin = in.readDouble();
        this.tempMax = in.readDouble();
        this.humMin = in.readDouble();
        this.humMax = in.readDouble();
        this.isOutLimit = in.readByte() != 0;
        this.dataarray = in.readString();
        this.humidityArray = in.readString();
        this.justTemp = in.readByte() != 0;
        this.roundCircle = in.readInt();
        this.number = in.readInt();
        this.havepost = in.readByte() != 0;
    }

    public static final Creator<TagInfo> CREATOR = new Creator<TagInfo>() {
        @Override
        public TagInfo createFromParcel(Parcel source) {
            return new TagInfo(source);
        }

        @Override
        public TagInfo[] newArray(int size) {
            return new TagInfo[size];
        }
    };
}
